.TH CICQCONV 1 "August 19, 2003"

.SH NAME
\fBcicqconv\fP

.SH SYNOPSIS
.B "cicqconv "
[
.B client
] ...

.SH DESCRIPTION
This manual page documents briefly the
.B cicqconv
command.
.PP
\fBcicqconv\fP is a tool for the centerim instant messaging client. It
can be used to convert contact lists and history from other IM clients.
So far the
.B client
parameter can be one of these: licq, kxicq2, gnomeicu, micq, trillian.

.SH AUTHOR
centerim as well as the cicqconv tool were originally written by Konstantin Klyagin.

.SH WEB
http://www.centerim.org/
