.TH CICQSYNC 1 "April 19, 2003"

.SH NAME
\fBcicqsync\fP

.SH SYNOPSIS
.B "cicqsync "
.B command
.B pathname

.SH DESCRIPTION
This manual page documents briefly the
.B cicqsync
command.
.PP
\fBcicqsync\fP is a tool for the
.B centericq
instant messaging client. It can be used to fetch the latest sources of the
program from CVS.
.B command
can be either "checkout" or "update", and
.B pathname
is location of the centericq source directory.

.SH AUTHOR
centericq was written by Konstantin Klyagin
<konst@konst.org.ua>.

.SH WEB
http://konst.org.ua/centericq/
