.TH CICQSYNC 1 "April 19, 2003"

.SH NAME
\fBcicqsync\fP

.SH SYNOPSIS
.B "cicqsync "
.B command
.B pathname

.SH DESCRIPTION
This manual page documents briefly the
.B cicqsync
command.
.PP
\fBcicqsync\fP is an outdated tool for the
.B centerim
instant messaging client. It can be used to fetch the latest sources of the
program from CVS.
.B command
can be either "checkout" or "update", and
.B pathname
is location of the centerim source directory.

.SH AUTHOR
centerim was originally written by Konstantin Klyagin.

.SH WEB
http://www.centerim.org/
