.TH cimconv 1 "August 19, 2003"

.SH NAME
\fBcimconv\fP

.SH SYNOPSIS
.B "cimconv "
[
.B client
] ...

.SH DESCRIPTION
This manual page documents briefly the
.B cimconv
command.
.PP
\fBcimconv\fP is a tool for the centerim instant messaging client. It
can be used to convert contact lists and history from other IM clients.
So far the
.B client
parameter can be one of these: licq, kxicq2, gnomeicu, micq, trillian.

.SH AUTHOR
centerim as well as the cimconv tool were written by Konstantin Klyagin
<k@thekonst.net>.

.SH WEB
http://www.centerim.org/
