.TH CENTERICQ 1 "November 22, 2001"

.SH NAME
\fBcentericq\fP \- text mode based IM client for Linux, *BSD and possibly,
other Unices. ICQ and Yahoo protocols are now supported.

.SH SYNOPSIS
.B "centericq "
[
.B option
] ...

.SH DESCRIPTION
This manual page documents briefly the
.B centericq
command.
.PP
\fBcentericq\fP is a text mode menu- and window-driven IM interface.
Currently ICQ and Yahoo protocols are supported. It allows you to send,
receive, and forward messages, URLs and, contacts, mass message send,
search for users (including extended "whitepages search"), view users' details,
maintain your contact list directly from the program (including non-icq
contacts), view the messages history, register a new UIN and update your
details, be informed on receiving email messages, automatically set away
after the defined period of inactivity (on any console), and have your own
ignore, visible and invisible lists. It can also associate events with
sounds, has support for Hebrew and Arabic languages and allows to arrange
contacts into groups.

.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-ascii\fR
use ascii characters to draw lines and boxes
.TP
\fB\-h\fR, \fB\-\-help\fR
display command line usage

.SH VERSION
centericq 4.1.0

.SH BUG REPORT
Report any bugs to centericq-bugs@konst.org.ua

.SH AUTHOR
This page and the centericq itself are written by Konstatin Klyagin
<konst@konst.org.ua>.

.SH WEB
http://konst.org.ua/centericq/
