.TH CENTERICQ 1 "August 21, 2003"

.SH NAME
\fBcentericq\fP \- a text mode based IM client for Linux, *BSD, Sun
Solaris, MacOS X and possibly, other Unices. ICQ2000, Yahoo!, AIM TOC,
IRC, MSN, Gadu-Gadu and Jabber protocols are now supported. Internal
LiveJournal client and RSS reader are also provided.

.SH SYNOPSIS
.B "centericq "
[
.B option
] ...

.SH DESCRIPTION
This manual page documents briefly the
.B centericq
command.
.PP
\fBcentericq\fP is a text mode menu- and window-driven IM interface.
Currently ICQ2000, Yahoo!, AIM, IRC, MSN, Gadu-Gadu and Jabber protocols
are supported. It allows you to send, receive, and forward messages,
URLs, SMSes and, contacts, mass message send, search for users
(including extended "whitepages search"), view users' details, maintain
your contact list directly from the program (including non-icq
contacts), view the messages history, register a new UIN and update your
details, be informed on receiving email messages, automatically set away
after the defined period of inactivity (on any console), and have your
own ignore, visible and invisible lists. It can also associate events
with sounds, add events to the outgoing queue from command line, define
external event processing actions (like events auto-forwarding or
elizatalk), has support for Hebrew and Arabic languages and allows to
arrange contacts into groups.

.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-ascii\fR
use ascii characters to draw lines and boxes
.TP
\fB\-h\fR, \fB\-\-help\fR
display command line usage
.TP
\fB\-v\fR, \fB\-\-version\fR
show the program version info
.TP
\fB\-b\fR, \fB\-\-basedir\fR <directory>
specify another base directory; useful for having several IM identities
under the same UNIX account
.TP
\fB\-B\fR, \fB\-\-bind\fR <hostname/ip>
tells centericq to use the specified IP address for outgoing connections
.TP
\fB\-B\fR, \fB\-\-no\-xtitles\fR
disable title changing in xterm or screen
.TP
\fB\-o\fR, \fB\-\-offline\fR
start with all protocols set offline

.PP

The following commands are used to put events to the outgoing queue from
the command line. If centericq is already running they're to be sent
immediately, otherwise they will be sent as soon as you go online.


.TP
\fB\-s\fR, \fB\-\-send\fR <event type>
This parameter specifies the type of event you want to send.
Currently only "msg", "url" and "sms" are supported.
.TP
\fB\-p\fR, \fB\-\-proto\fR <protocol type>
This one specifies to which IM network the destination contact
belongs. Can be "icq", "yahoo", "aim", "irc", "jab", "msn", "gg" or "lj".
.TP
\fB\-t\fR, \fB\-\-to\fR <nickname or UIN>
With this one you specify nickname or UIN of the
destination contact. For icq it's possible to specify 0 to send
events to yourself. Only SMSes are known to be possible to be sent
to oneself though.
.TP
\fB\-n\fR, \fB\-\-number\fR <phone number>
Using this parameter you can send SMSes to any mobile numbers
through the ICQ network.

.PP

The message text is read from the standard input, so use pipes in shell
to pass it. For example, you can say "hi" to me through the ICQ network
with the following command:

    \fB$ echo "hi" | centericq -s msg -p icq -t 17502151\fR

In case you want to send an URL, the URL itself and its description are
separated with a newline character the following way:

    \fB$ echo -e "http://thekonst.net/\\nMy modest homepage." \
    | centericq -s url -p icq -t 17502151\fR

Please note, that all three parameters are required in order to queue an
event.

Finally, a small example of sending SMSes:

    \fB$ echo "sms test" | centericq -s sms -n 1234567890\fR

.PP


It's also possible to change your current status on a particular IM
network with the following command line option.

.TP
\fB\-S\fR, \fB\-\-status\fR <status letter>
The argument parameter is a letter which indicates which status is
to be set: o (Online), _ (Offline), a (Away), d (Don't disturb), n (N/A),
c (Occupied), f (Free for chat), i (Invisible)
.TP
\fB\-p\fR or \fB\-\-proto\fR <protocol name>
Exactly the same like it was described for the previous command.

.PP


Examples:

    \fB$ centericq -S _ -p icq\fR

This will set the icq status to offline. In other words, it'll be
disconnected immediately.

    \fB$ centericq -S a -p yahoo\fR

And this command will switch your yahoo status to away.


.SH VERSION
centericq 4.20.0

.SH BUG REPORT
Report any bugs to centericq-bugs@konst.org.ua

.SH AUTHOR
This page and centericq itself are written by Konstantin Klyagin
<konst@konst.org.ua>.

.SH WEB
http://thekonst.net/centericq/
